/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presentation;

import bd.BaseDatos;
import bd.Conexion;
import controllers.MainController;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import logic.Expense;
import logic.Fuel;
import logic.Vehicle;
import presentation.dialogue.AddExpenseDialogue;
import presentation.dialogue.AddFuelDialogue;
import presentation.dialogue.AddVehicleDialogue;
import presentation.dialogue.DetailVehicleDialogue;
import presentation.logic.ConfigTables;
import presentation.logic.ConvertCalendar;
import presentation.logic.MainWindowPresentation;
import presentation.logic.TableManager;

/**
 *
 * @author Alejo
 */
public class MainWindow extends javax.swing.JFrame 
{
    private MainWindowPresentation presentation;
    private ConfigTables configTables;
    private MainController controller;
    private TableManager tableManager;
    private ConvertCalendar calendar;

    /**
     * Creates new form MainWindow
     */
    public MainWindow() 
    {
//JOptionPane.showMessageDialog(this, "pasa ===> 3");
        initComponents();
        this.txtTotalExpenses.setText("0");
        this.presentation = new MainWindowPresentation();
        this.configTables = new ConfigTables(this.tableFuel, this.tableVehicles,
                            this.tableExpenses);
        this.tableManager = new TableManager();
        Conexion con = new Conexion();
        BaseDatos bd = new BaseDatos(con);
        this.calendar = new ConvertCalendar();
        
        this.controller = new MainController(bd, this.configTables);
        this.setLocationRelativeTo(null);
        this.presentation.refreshPanel(this.mainMenu, this.panHome);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panMain = new javax.swing.JPanel();
        panOptions = new javax.swing.JPanel();
        txtFuel = new javax.swing.JLabel();
        txtvehicle = new javax.swing.JLabel();
        txtExpense = new javax.swing.JLabel();
        txtHome = new javax.swing.JLabel();
        panLogoLeft = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        panHeader = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        mainMenu = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        panHome = new javax.swing.JPanel();
        panNewFuel = new javax.swing.JPanel();
        txtNewFuel = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        panNewVehicle = new javax.swing.JPanel();
        txtNewVehicle = new javax.swing.JLabel();
        panNewExpense = new javax.swing.JPanel();
        txtNewExpense = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtExit = new javax.swing.JLabel();
        panExpense = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tableExpenses = new javax.swing.JTable();
        jSeparator3 = new javax.swing.JSeparator();
        btnAddExpense = new javax.swing.JButton();
        btnEditExpense = new javax.swing.JButton();
        btnDeleteExpense = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        txtTotalExpenses = new javax.swing.JLabel();
        jSeparator8 = new javax.swing.JSeparator();
        finishDateExpense = new com.toedter.calendar.JDateChooser();
        btnSearchExpense = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        initialDateExpense = new com.toedter.calendar.JDateChooser();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jSeparator9 = new javax.swing.JSeparator();
        panVehicle = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableVehicles = new javax.swing.JTable();
        jSeparator2 = new javax.swing.JSeparator();
        btnAddVehicle = new javax.swing.JButton();
        btnEditVehicle = new javax.swing.JButton();
        btnDeleteVehicle = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        btnViewExpense = new javax.swing.JButton();
        panFuel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableFuel = new javax.swing.JTable();
        jSeparator1 = new javax.swing.JSeparator();
        btnAddFuel = new javax.swing.JButton();
        btnEditFuel = new javax.swing.JButton();
        btnDeleteFuel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panMain.setBackground(new java.awt.Color(0, 0, 0));

        panOptions.setBackground(new java.awt.Color(36, 52, 81));

        txtFuel.setBackground(new java.awt.Color(255, 255, 255));
        txtFuel.setFont(new java.awt.Font("Candara", 1, 18)); // NOI18N
        txtFuel.setForeground(new java.awt.Color(255, 255, 255));
        txtFuel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/fuel-icon.png"))); // NOI18N
        txtFuel.setText("Combustibles");
        txtFuel.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                txtFuelMouseDragged(evt);
            }
        });
        txtFuel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtFuelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtFuelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtFuelMouseExited(evt);
            }
        });

        txtvehicle.setBackground(new java.awt.Color(255, 255, 255));
        txtvehicle.setFont(new java.awt.Font("Candara", 1, 18)); // NOI18N
        txtvehicle.setForeground(new java.awt.Color(255, 255, 255));
        txtvehicle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/vehicle-icon.png"))); // NOI18N
        txtvehicle.setText("     Vehículos");
        txtvehicle.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                txtvehicleMouseDragged(evt);
            }
        });
        txtvehicle.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtvehicleMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtvehicleMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtvehicleMouseExited(evt);
            }
        });

        txtExpense.setBackground(new java.awt.Color(255, 255, 255));
        txtExpense.setFont(new java.awt.Font("Candara", 1, 18)); // NOI18N
        txtExpense.setForeground(new java.awt.Color(255, 255, 255));
        txtExpense.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/expense-icon.png"))); // NOI18N
        txtExpense.setText("       Gastos");
        txtExpense.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                txtExpenseMouseDragged(evt);
            }
        });
        txtExpense.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtExpenseMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtExpenseMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtExpenseMouseExited(evt);
            }
        });

        txtHome.setBackground(new java.awt.Color(255, 255, 255));
        txtHome.setFont(new java.awt.Font("Candara", 1, 18)); // NOI18N
        txtHome.setForeground(new java.awt.Color(255, 255, 255));
        txtHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/home-icon.png"))); // NOI18N
        txtHome.setText("        Inicio");
        txtHome.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                txtHomeMouseDragged(evt);
            }
        });
        txtHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtHomeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtHomeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtHomeMouseExited(evt);
            }
        });

        javax.swing.GroupLayout panOptionsLayout = new javax.swing.GroupLayout(panOptions);
        panOptions.setLayout(panOptionsLayout);
        panOptionsLayout.setHorizontalGroup(
            panOptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panOptionsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panOptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtvehicle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtFuel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtExpense, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtHome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        panOptionsLayout.setVerticalGroup(
            panOptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panOptionsLayout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(txtHome, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtvehicle, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtFuel, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtExpense, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panLogoLeft.setBackground(new java.awt.Color(0, 0, 51));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/alcaldia-icon2.PNG"))); // NOI18N

        javax.swing.GroupLayout panLogoLeftLayout = new javax.swing.GroupLayout(panLogoLeft);
        panLogoLeft.setLayout(panLogoLeftLayout);
        panLogoLeftLayout.setHorizontalGroup(
            panLogoLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panLogoLeftLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        panLogoLeftLayout.setVerticalGroup(
            panLogoLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panLogoLeftLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        panHeader.setBackground(new java.awt.Color(0, 0, 41));

        jLabel1.setFont(new java.awt.Font("Cambria", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Control - Consumo de Combustible");

        jLabel2.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Alcaldía - Aguadas, Caldas");

        javax.swing.GroupLayout panHeaderLayout = new javax.swing.GroupLayout(panHeader);
        panHeader.setLayout(panHeaderLayout);
        panHeaderLayout.setHorizontalGroup(
            panHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panHeaderLayout.createSequentialGroup()
                .addGap(175, 175, 175)
                .addGroup(panHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panHeaderLayout.createSequentialGroup()
                        .addGap(180, 180, 180)
                        .addComponent(jLabel2))
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 588, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panHeaderLayout.setVerticalGroup(
            panHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panHeaderLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        mainMenu.setBackground(new java.awt.Color(255, 255, 255));
        mainMenu.setLayout(new java.awt.CardLayout());

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 964, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 512, Short.MAX_VALUE)
        );

        mainMenu.add(jPanel4, "card4");

        panNewFuel.setBackground(new java.awt.Color(255, 255, 255));
        panNewFuel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panNewFuelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panNewFuelMouseExited(evt);
            }
        });

        txtNewFuel.setBackground(new java.awt.Color(255, 255, 255));
        txtNewFuel.setFont(new java.awt.Font("Californian FB", 1, 18)); // NOI18N
        txtNewFuel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/42568fuelpump_98960.png"))); // NOI18N
        txtNewFuel.setText("  Combustible");
        txtNewFuel.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(102, 102, 102), new java.awt.Color(102, 102, 102)));
        txtNewFuel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtNewFuelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtNewFuelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtNewFuelMouseExited(evt);
            }
        });

        javax.swing.GroupLayout panNewFuelLayout = new javax.swing.GroupLayout(panNewFuel);
        panNewFuel.setLayout(panNewFuelLayout);
        panNewFuelLayout.setHorizontalGroup(
            panNewFuelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtNewFuel, javax.swing.GroupLayout.DEFAULT_SIZE, 227, Short.MAX_VALUE)
        );
        panNewFuelLayout.setVerticalGroup(
            panNewFuelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtNewFuel, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE)
        );

        jLabel12.setFont(new java.awt.Font("Cambria", 1, 48)); // NOI18N
        jLabel12.setText("Panel de Inicio");

        panNewVehicle.setBackground(new java.awt.Color(255, 255, 255));
        panNewVehicle.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panNewVehicleMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panNewVehicleMouseExited(evt);
            }
        });

        txtNewVehicle.setBackground(new java.awt.Color(255, 255, 255));
        txtNewVehicle.setFont(new java.awt.Font("Californian FB", 1, 18)); // NOI18N
        txtNewVehicle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Truck_Yellow_icon-icons.com_54884.png"))); // NOI18N
        txtNewVehicle.setText("     Vehículo");
        txtNewVehicle.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(102, 102, 102), new java.awt.Color(102, 102, 102)));
        txtNewVehicle.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtNewVehicleMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtNewVehicleMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtNewVehicleMouseExited(evt);
            }
        });

        javax.swing.GroupLayout panNewVehicleLayout = new javax.swing.GroupLayout(panNewVehicle);
        panNewVehicle.setLayout(panNewVehicleLayout);
        panNewVehicleLayout.setHorizontalGroup(
            panNewVehicleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtNewVehicle, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 227, Short.MAX_VALUE)
        );
        panNewVehicleLayout.setVerticalGroup(
            panNewVehicleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtNewVehicle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        panNewExpense.setBackground(new java.awt.Color(255, 255, 255));
        panNewExpense.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panNewExpenseMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panNewExpenseMouseExited(evt);
            }
        });

        txtNewExpense.setBackground(new java.awt.Color(255, 255, 255));
        txtNewExpense.setFont(new java.awt.Font("Californian FB", 1, 18)); // NOI18N
        txtNewExpense.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cash_icon-icons.com_51090 (1).png"))); // NOI18N
        txtNewExpense.setText("      Gasto");
        txtNewExpense.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(102, 102, 102), new java.awt.Color(102, 102, 102)));
        txtNewExpense.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtNewExpenseMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtNewExpenseMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtNewExpenseMouseExited(evt);
            }
        });

        javax.swing.GroupLayout panNewExpenseLayout = new javax.swing.GroupLayout(panNewExpense);
        panNewExpense.setLayout(panNewExpenseLayout);
        panNewExpenseLayout.setHorizontalGroup(
            panNewExpenseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtNewExpense, javax.swing.GroupLayout.DEFAULT_SIZE, 207, Short.MAX_VALUE)
        );
        panNewExpenseLayout.setVerticalGroup(
            panNewExpenseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtNewExpense, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jLabel13.setFont(new java.awt.Font("Cambria", 1, 24)); // NOI18N
        jLabel13.setText("Agregar Nuevo:");

        txtExit.setFont(new java.awt.Font("Cambria", 1, 24)); // NOI18N
        txtExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/exit-icon.png"))); // NOI18N
        txtExit.setText("   SALIR");
        txtExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtExitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtExitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtExitMouseExited(evt);
            }
        });

        javax.swing.GroupLayout panHomeLayout = new javax.swing.GroupLayout(panHome);
        panHome.setLayout(panHomeLayout);
        panHomeLayout.setHorizontalGroup(
            panHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panHomeLayout.createSequentialGroup()
                .addContainerGap(99, Short.MAX_VALUE)
                .addGroup(panHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panHomeLayout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addGap(307, 307, 307))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panHomeLayout.createSequentialGroup()
                        .addComponent(panNewFuel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(73, 73, 73)
                        .addGroup(panHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panHomeLayout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addGap(382, 382, 382))
                            .addGroup(panHomeLayout.createSequentialGroup()
                                .addComponent(panNewVehicle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(54, 54, 54)
                                .addComponent(panNewExpense, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(77, 77, 77))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panHomeLayout.createSequentialGroup()
                        .addComponent(txtExit, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(367, 367, 367))))
        );
        panHomeLayout.setVerticalGroup(
            panHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panHomeLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel13)
                .addGap(24, 24, 24)
                .addGroup(panHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(panNewVehicle, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panNewExpense, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panNewFuel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 104, Short.MAX_VALUE)
                .addComponent(txtExit)
                .addGap(70, 70, 70))
        );

        mainMenu.add(panHome, "card4");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel6.setText("GASTOS");

        jScrollPane3.setBackground(new java.awt.Color(153, 153, 0));

        tableExpenses.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(tableExpenses);

        jSeparator3.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N

        btnAddExpense.setBackground(new java.awt.Color(51, 255, 51));
        btnAddExpense.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        btnAddExpense.setForeground(new java.awt.Color(255, 255, 255));
        btnAddExpense.setText("Agregar");
        btnAddExpense.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddExpenseActionPerformed(evt);
            }
        });

        btnEditExpense.setBackground(new java.awt.Color(0, 51, 255));
        btnEditExpense.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        btnEditExpense.setForeground(new java.awt.Color(255, 255, 255));
        btnEditExpense.setText("Modificar");
        btnEditExpense.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditExpenseActionPerformed(evt);
            }
        });

        btnDeleteExpense.setBackground(new java.awt.Color(255, 51, 51));
        btnDeleteExpense.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        btnDeleteExpense.setForeground(new java.awt.Color(255, 255, 255));
        btnDeleteExpense.setText("Eliminar");
        btnDeleteExpense.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteExpenseActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Cambria", 1, 24)); // NOI18N
        jLabel7.setText("TOTAL:");

        txtTotalExpenses.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtTotalExpenses.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jSeparator8.setOrientation(javax.swing.SwingConstants.VERTICAL);

        btnSearchExpense.setBackground(new java.awt.Color(53, 144, 197));
        btnSearchExpense.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N
        btnSearchExpense.setForeground(new java.awt.Color(255, 255, 255));
        btnSearchExpense.setText("ACEPTAR");
        btnSearchExpense.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchExpenseActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Cambria", 0, 12)); // NOI18N
        jLabel9.setText("Final:");

        jLabel10.setFont(new java.awt.Font("Cambria", 0, 12)); // NOI18N
        jLabel10.setText("Inicial:");

        jLabel11.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        jLabel11.setText("Buscar Gastos Por Fecha: ");

        jSeparator9.setOrientation(javax.swing.SwingConstants.VERTICAL);

        javax.swing.GroupLayout panExpenseLayout = new javax.swing.GroupLayout(panExpense);
        panExpense.setLayout(panExpenseLayout);
        panExpenseLayout.setHorizontalGroup(
            panExpenseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panExpenseLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addGap(31, 31, 31)
                .addComponent(txtTotalExpenses, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
            .addGroup(panExpenseLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panExpenseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panExpenseLayout.createSequentialGroup()
                        .addGroup(panExpenseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator3)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 944, Short.MAX_VALUE))
                        .addContainerGap())
                    .addGroup(panExpenseLayout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(jSeparator9, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addGroup(panExpenseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panExpenseLayout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnSearchExpense, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18))
                            .addGroup(panExpenseLayout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(initialDateExpense, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(finishDateExpense, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(47, 47, 47)))
                        .addComponent(jSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnAddExpense, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnEditExpense, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14)
                        .addComponent(btnDeleteExpense, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25))))
        );
        panExpenseLayout.setVerticalGroup(
            panExpenseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panExpenseLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panExpenseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panExpenseLayout.createSequentialGroup()
                        .addGroup(panExpenseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panExpenseLayout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(13, 13, 13))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panExpenseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(btnAddExpense)
                                .addComponent(btnEditExpense)
                                .addComponent(btnDeleteExpense)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(panExpenseLayout.createSequentialGroup()
                        .addGroup(panExpenseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panExpenseLayout.createSequentialGroup()
                                .addGroup(panExpenseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel11)
                                    .addComponent(btnSearchExpense))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(panExpenseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(panExpenseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(finishDateExpense, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(initialDateExpense, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel9)))
                            .addComponent(jSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSeparator9, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(panExpenseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtTotalExpenses, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        mainMenu.add(panExpense, "card4");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel5.setText("Vehículos");

        jScrollPane2.setBackground(new java.awt.Color(153, 153, 0));

        tableVehicles.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tableVehicles);

        jSeparator2.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N

        btnAddVehicle.setBackground(new java.awt.Color(51, 255, 51));
        btnAddVehicle.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        btnAddVehicle.setForeground(new java.awt.Color(255, 255, 255));
        btnAddVehicle.setText("Agregar");
        btnAddVehicle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddVehicleActionPerformed(evt);
            }
        });

        btnEditVehicle.setBackground(new java.awt.Color(0, 51, 255));
        btnEditVehicle.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        btnEditVehicle.setForeground(new java.awt.Color(255, 255, 255));
        btnEditVehicle.setText("Modificar");
        btnEditVehicle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditVehicleActionPerformed(evt);
            }
        });

        btnDeleteVehicle.setBackground(new java.awt.Color(255, 51, 51));
        btnDeleteVehicle.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        btnDeleteVehicle.setForeground(new java.awt.Color(255, 255, 255));
        btnDeleteVehicle.setText("Eliminar");
        btnDeleteVehicle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteVehicleActionPerformed(evt);
            }
        });

        jSeparator4.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jSeparator5.setOrientation(javax.swing.SwingConstants.VERTICAL);

        btnViewExpense.setBackground(new java.awt.Color(0, 204, 204));
        btnViewExpense.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        btnViewExpense.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/eye-icon.png"))); // NOI18N
        btnViewExpense.setText("Ver Gastos");
        btnViewExpense.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewExpenseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panVehicleLayout = new javax.swing.GroupLayout(panVehicle);
        panVehicle.setLayout(panVehicleLayout);
        panVehicleLayout.setHorizontalGroup(
            panVehicleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panVehicleLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panVehicleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator2)
                    .addComponent(jScrollPane2))
                .addContainerGap())
            .addGroup(panVehicleLayout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addComponent(jLabel5)
                .addGap(32, 32, 32)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnViewExpense)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(79, 79, 79)
                .addComponent(btnAddVehicle, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnEditVehicle, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addComponent(btnDeleteVehicle, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );
        panVehicleLayout.setVerticalGroup(
            panVehicleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panVehicleLayout.createSequentialGroup()
                .addGroup(panVehicleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panVehicleLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(panVehicleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panVehicleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panVehicleLayout.createSequentialGroup()
                                    .addGroup(panVehicleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(btnAddVehicle)
                                        .addComponent(btnEditVehicle)
                                        .addComponent(btnDeleteVehicle))
                                    .addGap(18, 18, 18))
                                .addGroup(panVehicleLayout.createSequentialGroup()
                                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGap(13, 13, 13))
                                .addGroup(panVehicleLayout.createSequentialGroup()
                                    .addComponent(jSeparator4)
                                    .addGap(6, 6, 6)))
                            .addGroup(panVehicleLayout.createSequentialGroup()
                                .addComponent(jSeparator5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panVehicleLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnViewExpense)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 417, Short.MAX_VALUE)
                .addContainerGap())
        );

        mainMenu.add(panVehicle, "card3");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel3.setText("Combustibles");

        jScrollPane1.setBackground(new java.awt.Color(153, 153, 0));

        tableFuel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tableFuel);

        jSeparator1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N

        btnAddFuel.setBackground(new java.awt.Color(51, 255, 51));
        btnAddFuel.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        btnAddFuel.setForeground(new java.awt.Color(255, 255, 255));
        btnAddFuel.setText("Agregar");
        btnAddFuel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddFuelActionPerformed(evt);
            }
        });

        btnEditFuel.setBackground(new java.awt.Color(0, 51, 255));
        btnEditFuel.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        btnEditFuel.setForeground(new java.awt.Color(255, 255, 255));
        btnEditFuel.setText("Modificar");
        btnEditFuel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditFuelActionPerformed(evt);
            }
        });

        btnDeleteFuel.setBackground(new java.awt.Color(255, 51, 51));
        btnDeleteFuel.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        btnDeleteFuel.setForeground(new java.awt.Color(255, 255, 255));
        btnDeleteFuel.setText("Eliminar");
        btnDeleteFuel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteFuelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panFuelLayout = new javax.swing.GroupLayout(panFuel);
        panFuel.setLayout(panFuelLayout);
        panFuelLayout.setHorizontalGroup(
            panFuelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panFuelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panFuelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addComponent(jScrollPane1))
                .addContainerGap())
            .addGroup(panFuelLayout.createSequentialGroup()
                .addGap(147, 147, 147)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 170, Short.MAX_VALUE)
                .addComponent(btnAddFuel, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnEditFuel, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addComponent(btnDeleteFuel, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );
        panFuelLayout.setVerticalGroup(
            panFuelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panFuelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panFuelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panFuelLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(13, 13, 13))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panFuelLayout.createSequentialGroup()
                        .addGroup(panFuelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnAddFuel)
                            .addComponent(btnEditFuel)
                            .addComponent(btnDeleteFuel))
                        .addGap(18, 18, 18)))
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 417, Short.MAX_VALUE)
                .addContainerGap())
        );

        mainMenu.add(panFuel, "card2");

        javax.swing.GroupLayout panMainLayout = new javax.swing.GroupLayout(panMain);
        panMain.setLayout(panMainLayout);
        panMainLayout.setHorizontalGroup(
            panMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panMainLayout.createSequentialGroup()
                .addGroup(panMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panOptions, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panLogoLeft, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panHeader, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(mainMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        panMainLayout.setVerticalGroup(
            panMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panMainLayout.createSequentialGroup()
                .addGroup(panMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panHeader, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panLogoLeft, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panOptions, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(mainMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtFuelMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtFuelMouseDragged
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFuelMouseDragged

    private void txtFuelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtFuelMouseClicked
        this.presentation.refreshPanel(this.mainMenu, this.panFuel);
        this.controller.indexFuel();
    }//GEN-LAST:event_txtFuelMouseClicked

    private void txtFuelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtFuelMouseEntered
        this.presentation.runInteractiveButton(this.txtFuel, true);
    }//GEN-LAST:event_txtFuelMouseEntered

    private void txtFuelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtFuelMouseExited
        this.presentation.runInteractiveButton(this.txtFuel, false);
    }//GEN-LAST:event_txtFuelMouseExited

    private void btnAddFuelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddFuelActionPerformed
        AddFuelDialogue addFuel = new AddFuelDialogue(this, true, this.controller);
        addFuel.setVisible(true);
        this.controller.indexFuel();
    }//GEN-LAST:event_btnAddFuelActionPerformed

    private void btnEditFuelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditFuelActionPerformed
        AddFuelDialogue addFuel = new AddFuelDialogue(this, true, this.controller);
        int id = this.tableManager.getIdElementFromTable(this.tableFuel);
        if(id == -1)
            JOptionPane.showMessageDialog(this, "Seleccione El Combustible Que Desea Modificar");
        else
        {
System.out.println("LO QUE SACOO: " + id);
            Fuel fuel = this.controller.getBd().getCrudFuel().getFuel(id);
            addFuel.bindingModel(fuel);
            addFuel.setVisible(true);
            this.controller.indexFuel();
        }

    }//GEN-LAST:event_btnEditFuelActionPerformed

    private void btnDeleteFuelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteFuelActionPerformed
        int id = this.tableManager.getIdElementFromTable(this.tableFuel);
        if(id == -1)
            JOptionPane.showMessageDialog(this, "Seleccione El Combustible Que Desea Eliminar");
        else
        {
            int opc = JOptionPane.showConfirmDialog(null, "Realmente desea eliminar el combustible?",
                "Confirmar", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
            //0 para si || 1 para no
            if (opc == 0)
            {
                boolean check = this.controller.getFuelController().delete(id);
                if(check)
                {
                    JOptionPane.showMessageDialog(this, "Combustible eliminado correctamente");
                    this.controller.indexFuel();
                }
            }
        }
    }//GEN-LAST:event_btnDeleteFuelActionPerformed

    private void txtvehicleMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtvehicleMouseDragged
        // TODO add your handling code here:
    }//GEN-LAST:event_txtvehicleMouseDragged

    private void txtvehicleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtvehicleMouseClicked
        this.presentation.refreshPanel(this.mainMenu, this.panVehicle);
        this.controller.indexVehicle();
    }//GEN-LAST:event_txtvehicleMouseClicked

    private void txtvehicleMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtvehicleMouseEntered
        this.presentation.runInteractiveButton(this.txtvehicle, true);
    }//GEN-LAST:event_txtvehicleMouseEntered

    private void txtvehicleMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtvehicleMouseExited
        this.presentation.runInteractiveButton(this.txtvehicle, false);
    }//GEN-LAST:event_txtvehicleMouseExited

    private void btnAddVehicleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddVehicleActionPerformed
        ArrayList<Fuel> fuels = this.controller.getFuelController().index();
        AddVehicleDialogue addVehicle = new AddVehicleDialogue(this, true, fuels, this.controller);
        addVehicle.setVisible(true);
        this.controller.indexVehicle();
    }//GEN-LAST:event_btnAddVehicleActionPerformed

    private void btnEditVehicleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditVehicleActionPerformed
        ArrayList<Fuel> fuels = this.controller.getFuelController().index();
        AddVehicleDialogue addVehicle = new AddVehicleDialogue(this, true, fuels, controller);
        int id = this.tableManager.getIdElementFromTable(this.tableVehicles);
        if(id == -1)
            JOptionPane.showMessageDialog(this, "Seleccione El Vehículo Que Desea Modificar");
        else
        {
            Vehicle vehicle = this.controller.getBd().getCrudVehicle().getVehicle(id);
//System.out.println(vehicle);
//System.out.println("ID ==> " + id);
            addVehicle.bindingModel(vehicle);
            addVehicle.setVisible(true);
            this.controller.indexVehicle();
        }
    }//GEN-LAST:event_btnEditVehicleActionPerformed

    private void btnDeleteVehicleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteVehicleActionPerformed
        int id = this.tableManager.getIdElementFromTable(this.tableVehicles);
        if(id == -1)
            JOptionPane.showMessageDialog(this, "Seleccione El Vehículo Que Desea Eliminar");
        else
        {
            int opc = JOptionPane.showConfirmDialog(null, "Realmente desea eliminar el vehículo?",
                "Confirmar", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
            //0 para si || 1 para no
            if (opc == 0)
            {
                boolean check = this.controller.getVehicleController().delete(id);
                if(check)
                {
                    JOptionPane.showMessageDialog(this, "Vehículo eliminado correctamente");
                    this.controller.indexVehicle();
                }
            }
        }
    }//GEN-LAST:event_btnDeleteVehicleActionPerformed

    private void txtExpenseMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtExpenseMouseDragged
        // TODO add your handling code here:
    }//GEN-LAST:event_txtExpenseMouseDragged

    private void txtExpenseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtExpenseMouseClicked
        this.presentation.refreshPanel(this.mainMenu, this.panExpense);
        String[] dates = this.calendar.runPagination();
        this.controller.indexExpenseWithDate(dates[0], dates[1], this.txtTotalExpenses);
    }//GEN-LAST:event_txtExpenseMouseClicked

    private void txtExpenseMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtExpenseMouseEntered
        this.presentation.runInteractiveButton(this.txtExpense, true);
    }//GEN-LAST:event_txtExpenseMouseEntered

    private void txtExpenseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtExpenseMouseExited
        this.presentation.runInteractiveButton(this.txtExpense, false);
    }//GEN-LAST:event_txtExpenseMouseExited

    private void btnAddExpenseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddExpenseActionPerformed
        ArrayList<Vehicle> vehicles = this.controller.getVehicleController().index();
        AddExpenseDialogue addExpense = new AddExpenseDialogue(this, true, vehicles, this.controller);
        addExpense.setVisible(true);
        String[] dates = this.calendar.runPagination();
        this.controller.indexExpenseWithDate(dates[0], dates[1], this.txtTotalExpenses);
    }//GEN-LAST:event_btnAddExpenseActionPerformed

    private void btnEditExpenseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditExpenseActionPerformed
        ArrayList<Vehicle> vehicles = this.controller.getVehicleController().index();
        AddExpenseDialogue addExpense = new AddExpenseDialogue(this, true, vehicles, this.controller);
        int id = this.tableManager.getIdElementFromTable(this.tableExpenses);
        if(id == -1)
        {
            JOptionPane.showMessageDialog(this, "Seleccione El Gasto Que Desea Modificar");
        }
        else
        {
            Expense expense = this.controller.getBd().getCrudExpense().getExpense(id);
            addExpense.bindingModel(expense);
            addExpense.setVisible(true);
            this.controller.indexExpense();
            
            String[] dates = this.calendar.runPagination();
            this.controller.indexExpenseWithDate(dates[0], dates[1], this.txtTotalExpenses);            
        }
    }//GEN-LAST:event_btnEditExpenseActionPerformed

    private void btnDeleteExpenseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteExpenseActionPerformed
        int id = this.tableManager.getIdElementFromTable(this.tableExpenses);
        if(id == -1)
            JOptionPane.showMessageDialog(this, "Seleccione El Combustible Que Desea Eliminar");
        else
        {
            int opc = JOptionPane.showConfirmDialog(null, "Realmente desea eliminar el combustible?",
                "Confirmar", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
            //0 para si || 1 para no
            if (opc == 0)
            {
                boolean check = this.controller.getExpenseController().delete(id);
                if(check)
                {
                    JOptionPane.showMessageDialog(this, "Gasto eliminado correctamente");
                    String[] dates = this.calendar.runPagination();
                    this.controller.indexExpenseWithDate(dates[0], dates[1], this.txtTotalExpenses);
                }
            }
        }
    }//GEN-LAST:event_btnDeleteExpenseActionPerformed

    private void btnSearchExpenseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchExpenseActionPerformed
        String[] dates = this.calendar.getSearchDates(this.initialDateExpense.getCalendar(), 
                                        this.finishDateExpense.getCalendar());
        if(dates == null)
            JOptionPane.showMessageDialog(this, "ERROR, Seleccione Una Fecha Inicial y Final");
        else
        {
            this.controller.indexExpenseWithDate(dates[0], dates[1], this.txtTotalExpenses);
        }
    }//GEN-LAST:event_btnSearchExpenseActionPerformed

    private void txtHomeMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtHomeMouseDragged
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHomeMouseDragged

    private void txtHomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtHomeMouseClicked
        this.presentation.refreshPanel(this.mainMenu, this.panHome);
    }//GEN-LAST:event_txtHomeMouseClicked

    private void txtHomeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtHomeMouseEntered
        this.presentation.runInteractiveButton(this.txtHome, true);
    }//GEN-LAST:event_txtHomeMouseEntered

    private void txtHomeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtHomeMouseExited
        this.presentation.runInteractiveButton(this.txtHome, false);
    }//GEN-LAST:event_txtHomeMouseExited

    private void txtNewFuelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtNewFuelMouseClicked
        AddFuelDialogue addFuel = new AddFuelDialogue(this, true, this.controller);
        addFuel.setVisible(true);
        this.controller.indexFuel();
    }//GEN-LAST:event_txtNewFuelMouseClicked

    private void txtNewFuelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtNewFuelMouseEntered
        this.presentation.runInteractiveButton(this.panNewFuel, this.txtNewFuel, true);
    }//GEN-LAST:event_txtNewFuelMouseEntered

    private void txtNewFuelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtNewFuelMouseExited
        this.presentation.runInteractiveButton(this.panNewFuel, this.txtNewFuel, false);
    }//GEN-LAST:event_txtNewFuelMouseExited

    private void panNewFuelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panNewFuelMouseEntered
        this.presentation.runInteractiveButton(this.panNewFuel, this.txtNewFuel, true);
    }//GEN-LAST:event_panNewFuelMouseEntered

    private void panNewFuelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panNewFuelMouseExited
        this.presentation.runInteractiveButton(this.panNewFuel, this.txtNewFuel, false);
    }//GEN-LAST:event_panNewFuelMouseExited

    private void txtNewVehicleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtNewVehicleMouseClicked
        ArrayList<Fuel> fuels = this.controller.getFuelController().index();
        AddVehicleDialogue addVehicle = new AddVehicleDialogue(this, true, fuels, this.controller);
        addVehicle.setVisible(true);
        this.controller.indexVehicle();
    }//GEN-LAST:event_txtNewVehicleMouseClicked

    private void txtNewVehicleMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtNewVehicleMouseEntered
        this.presentation.runInteractiveButton(this.panNewVehicle, this.txtNewVehicle, true);
    }//GEN-LAST:event_txtNewVehicleMouseEntered

    private void txtNewVehicleMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtNewVehicleMouseExited
        this.presentation.runInteractiveButton(this.panNewVehicle, this.txtNewVehicle, false);
    }//GEN-LAST:event_txtNewVehicleMouseExited

    private void panNewVehicleMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panNewVehicleMouseEntered
        
    }//GEN-LAST:event_panNewVehicleMouseEntered

    private void panNewVehicleMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panNewVehicleMouseExited
        
    }//GEN-LAST:event_panNewVehicleMouseExited

    private void txtNewExpenseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtNewExpenseMouseClicked
        ArrayList<Vehicle> vehicles = this.controller.getVehicleController().index();
        AddExpenseDialogue addExpense = new AddExpenseDialogue(this, true, vehicles, this.controller);
        addExpense.setVisible(true);
        String[] dates = this.calendar.runPagination();
        this.controller.indexExpenseWithDate(dates[0], dates[1], this.txtTotalExpenses);
        this.controller.indexExpense();
    }//GEN-LAST:event_txtNewExpenseMouseClicked

    private void txtNewExpenseMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtNewExpenseMouseEntered
        this.presentation.runInteractiveButton(this.panNewExpense, this.txtNewExpense, true);
    }//GEN-LAST:event_txtNewExpenseMouseEntered

    private void txtNewExpenseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtNewExpenseMouseExited
        this.presentation.runInteractiveButton(this.panNewExpense, this.txtNewExpense, false);
    }//GEN-LAST:event_txtNewExpenseMouseExited

    private void panNewExpenseMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panNewExpenseMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_panNewExpenseMouseEntered

    private void panNewExpenseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panNewExpenseMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_panNewExpenseMouseExited

    private void txtExitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtExitMouseEntered
        this.presentation.runInteractiveButton(this.txtExit, true);
    }//GEN-LAST:event_txtExitMouseEntered

    private void txtExitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtExitMouseExited
        this.presentation.runInteractiveButton(this.txtExit, false);
    }//GEN-LAST:event_txtExitMouseExited

    private void txtExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtExitMouseClicked
        System.exit(0);
    }//GEN-LAST:event_txtExitMouseClicked

    private void btnViewExpenseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewExpenseActionPerformed
        int id = this.tableManager.getIdElementFromTable(this.tableVehicles);
        if(id == -1)
            JOptionPane.showMessageDialog(this, "Seleccione Un Vehículo!");
        else
        {
            Vehicle v = this.controller.getBd().getCrudVehicle().getVehicle(id);
            DetailVehicleDialogue dv = new DetailVehicleDialogue(this, true, v, this.controller);
            dv.setVisible(true);
        }

    }//GEN-LAST:event_btnViewExpenseActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddExpense;
    private javax.swing.JButton btnAddFuel;
    private javax.swing.JButton btnAddVehicle;
    private javax.swing.JButton btnDeleteExpense;
    private javax.swing.JButton btnDeleteFuel;
    private javax.swing.JButton btnDeleteVehicle;
    private javax.swing.JButton btnEditExpense;
    private javax.swing.JButton btnEditFuel;
    private javax.swing.JButton btnEditVehicle;
    private javax.swing.JButton btnSearchExpense;
    private javax.swing.JButton btnViewExpense;
    private com.toedter.calendar.JDateChooser finishDateExpense;
    private com.toedter.calendar.JDateChooser initialDateExpense;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JPanel mainMenu;
    private javax.swing.JPanel panExpense;
    private javax.swing.JPanel panFuel;
    private javax.swing.JPanel panHeader;
    private javax.swing.JPanel panHome;
    private javax.swing.JPanel panLogoLeft;
    private javax.swing.JPanel panMain;
    private javax.swing.JPanel panNewExpense;
    private javax.swing.JPanel panNewFuel;
    private javax.swing.JPanel panNewVehicle;
    private javax.swing.JPanel panOptions;
    private javax.swing.JPanel panVehicle;
    private javax.swing.JTable tableExpenses;
    private javax.swing.JTable tableFuel;
    private javax.swing.JTable tableVehicles;
    private javax.swing.JLabel txtExit;
    private javax.swing.JLabel txtExpense;
    private javax.swing.JLabel txtFuel;
    private javax.swing.JLabel txtHome;
    private javax.swing.JLabel txtNewExpense;
    private javax.swing.JLabel txtNewFuel;
    private javax.swing.JLabel txtNewVehicle;
    private javax.swing.JLabel txtTotalExpenses;
    private javax.swing.JLabel txtvehicle;
    // End of variables declaration//GEN-END:variables
}
