package presentation.dialogue;

import controllers.MainController;
import java.util.ArrayList;
import java.util.Calendar;
import javax.swing.JOptionPane;
import logic.Expense;
import logic.Vehicle;
import presentation.logic.ConvertCalendar;

/**
 *
 * @author Alejo
 */
public class AddExpenseDialogue extends javax.swing.JDialog 
{
    private Expense expense;
    private ArrayList<Vehicle> vehicles;
    private MainController controller;
    
    private ConvertCalendar calendar;
    
    /**
     * Creates new form AddExpenseDialogue
     */
    public AddExpenseDialogue(java.awt.Frame parent, boolean modal, 
            ArrayList<Vehicle> vehicles, MainController controller) 
    {
        super(parent, modal);
        this.calendar = new ConvertCalendar();
        this.vehicles = vehicles;
        this.expense = null;
        this.controller = controller;        
        initComponents();
        this.initInformation();
        this.setLocationRelativeTo(null);
    }
    
    public void initInformation()
    {
        this.combVehicles.removeAllItems();
        int numFuels = this.vehicles.size();
        Vehicle aux;
        
        for(int i = 0; i < numFuels; i++) 
        {
            aux = this.vehicles.get(i);
            this.combVehicles.addItem(aux.getId() + "# " + aux.getDescription());
        }
    }
    
    public void bindingModel(Expense expense)
    {
        this.expense = expense;
        this.lblTitle.setText("Modificar Gasto");
        String vehicleSelected = expense.getVehicle().getId() + "# " + expense.getVehicle()
                                                            .getDescription();
System.out.println("Vehiculo ==> " + vehicleSelected);
        this.combVehicles.setSelectedItem(vehicleSelected);
        this.dateChoss.setDate(this.calendar.convertStringToDate(expense.getDate()));
        this.txtInvoiceCode.setText(expense.getInvoiceCode());
        double countGal = expense.getValue() / (expense.getVehicle().getFuel().getValue());
        this.txtCountGal.setText(countGal + "");        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        txtInvoiceCode = new javax.swing.JTextField();
        lblNombre1 = new javax.swing.JLabel();
        btnCancel = new javax.swing.JButton();
        btnAddExpense = new javax.swing.JButton();
        combVehicles = new javax.swing.JComboBox<>();
        lblNombre2 = new javax.swing.JLabel();
        dateChoss = new com.toedter.calendar.JDateChooser();
        lblNombre3 = new javax.swing.JLabel();
        txtCountGal = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(102, 102, 102));

        lblTitle.setFont(new java.awt.Font("Cambria", 0, 28)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblTitle.setText("Agregar Gasto");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblTitle)
                .addGap(114, 114, 114))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblTitle)
                .addContainerGap())
        );

        lblNombre.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        lblNombre.setText("Vehículo:");

        txtInvoiceCode.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        txtInvoiceCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtInvoiceCodeActionPerformed(evt);
            }
        });

        lblNombre1.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        lblNombre1.setText("Cod. Factura:");

        btnCancel.setBackground(new java.awt.Color(255, 51, 51));
        btnCancel.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        btnCancel.setForeground(new java.awt.Color(255, 255, 255));
        btnCancel.setText("CANCELAR");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        btnAddExpense.setBackground(new java.awt.Color(51, 255, 51));
        btnAddExpense.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        btnAddExpense.setForeground(new java.awt.Color(255, 255, 255));
        btnAddExpense.setText("AGREGAR");
        btnAddExpense.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddExpenseActionPerformed(evt);
            }
        });

        combVehicles.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        combVehicles.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        lblNombre2.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        lblNombre2.setText("Fecha:");

        lblNombre3.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        lblNombre3.setText("Cantidad (GAL):");

        txtCountGal.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        txtCountGal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCountGalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblNombre3)
                                .addGap(18, 18, 18)
                                .addComponent(txtCountGal, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblNombre)
                                    .addComponent(lblNombre1)
                                    .addComponent(lblNombre2))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(54, 54, 54)
                                        .addComponent(dateChoss, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtInvoiceCode, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(combVehicles, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                        .addContainerGap(26, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAddExpense, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombre)
                    .addComponent(combVehicles, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblNombre2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(dateChoss, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombre1)
                    .addComponent(txtInvoiceCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombre3)
                    .addComponent(txtCountGal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancel)
                    .addComponent(btnAddExpense))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtInvoiceCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtInvoiceCodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtInvoiceCodeActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnAddExpenseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddExpenseActionPerformed
       String vehicle = (String)this.combVehicles.getSelectedItem();
       Calendar date = this.dateChoss.getCalendar();
       String invoiceCode = this.txtInvoiceCode.getText();
       
       //String value = this.txtValue.getText();
       
       if(this.expense == null) //Nuevo gasto.
       {
           boolean check = this.controller.getExpenseController().
                                    create(vehicle, date, invoiceCode, this.txtCountGal);

            if(check)
            {
                JOptionPane.showMessageDialog(this, "Gasto Agregado Correctamente!");
                this.dispose();
            }
            else
            {
                JOptionPane.showMessageDialog(this, "ERROR, Compruebe Los Datos Ingresados");
            }
       }
       else  //Modificar gasto.
       {
           boolean check = this.controller.getExpenseController().update
                    (this.expense, vehicle, date, invoiceCode, this.txtCountGal);
           if(check)
           {
               JOptionPane.showMessageDialog(this, "Gasto Actualizado Correctamente");
               this.dispose();
           }
           else
           {
               JOptionPane.showMessageDialog(this, "ERROR, Verifique Los Datos Ingresados");
           }           
       } 
    }//GEN-LAST:event_btnAddExpenseActionPerformed

    private void txtCountGalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCountGalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCountGalActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddExpense;
    private javax.swing.JButton btnCancel;
    private javax.swing.JComboBox<String> combVehicles;
    private com.toedter.calendar.JDateChooser dateChoss;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblNombre1;
    private javax.swing.JLabel lblNombre2;
    private javax.swing.JLabel lblNombre3;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTextField txtCountGal;
    private javax.swing.JTextField txtInvoiceCode;
    // End of variables declaration//GEN-END:variables
}
