package presentation.dialogue;

import controllers.MainController;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import logic.Fuel;
import logic.Vehicle;

/**
 *
 * @author Alejo
 */
public class AddVehicleDialogue extends javax.swing.JDialog 
{
    private Vehicle vehicle;
    private ArrayList<Fuel> fuels;
    private MainController controller;

    /**
     * Creates new form AddVehicleDialogue
     */
    public AddVehicleDialogue(java.awt.Frame parent, boolean modal,
            ArrayList<Fuel> fuels, MainController controller) 
    {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
        this.fuels = fuels;
        this.controller = controller;
        this.initInformation();
        
    }
    
    public void initInformation()
    {
        this.combFuels.removeAllItems();
        int numFuels = this.fuels.size();
        Fuel aux;
        
        for(int i = 0; i < numFuels; i++) 
        {
            aux = this.fuels.get(i);
            this.combFuels.addItem(aux.getId() + "# " + aux.getName());
        }
    }
    
    public int getIdFromComb(String selected)
    {
        String[] info = selected.split("#");
        int id = -1;
        try {
            id = Integer.parseInt(info[0]);
        } catch (Exception e) {
        }
        
        return id;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        txtDescription = new javax.swing.JTextField();
        lblNombre1 = new javax.swing.JLabel();
        btnCancel = new javax.swing.JButton();
        btnAddVehicle = new javax.swing.JButton();
        combFuels = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(102, 102, 102));

        lblTitle.setFont(new java.awt.Font("Cambria", 0, 28)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblTitle.setText("Agregar Vehículo");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(94, 94, 94)
                .addComponent(lblTitle)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitle)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lblNombre.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        lblNombre.setText("Descripción:");

        txtDescription.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        txtDescription.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDescriptionActionPerformed(evt);
            }
        });

        lblNombre1.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        lblNombre1.setText("Combustible:");

        btnCancel.setBackground(new java.awt.Color(255, 51, 51));
        btnCancel.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        btnCancel.setForeground(new java.awt.Color(255, 255, 255));
        btnCancel.setText("CANCELAR");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        btnAddVehicle.setBackground(new java.awt.Color(51, 255, 51));
        btnAddVehicle.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        btnAddVehicle.setForeground(new java.awt.Color(255, 255, 255));
        btnAddVehicle.setText("AGREGAR");
        btnAddVehicle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddVehicleActionPerformed(evt);
            }
        });

        combFuels.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        combFuels.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                        .addComponent(btnAddVehicle, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(47, 47, 47))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblNombre)
                            .addComponent(lblNombre1))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtDescription, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                            .addComponent(combFuels, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombre)
                    .addComponent(txtDescription, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombre1)
                    .addComponent(combFuels, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddVehicle)
                    .addComponent(btnCancel))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtDescriptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDescriptionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDescriptionActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnAddVehicleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddVehicleActionPerformed
        String description = this.txtDescription.getText();
        String fuel = (String)this.combFuels.getSelectedItem();
        int id = this.getIdFromComb(fuel);
        if(id > 0)
        {
            if(this.vehicle == null)//Si se desea crear.
            {
                boolean flag = this.controller.getVehicleController().create(description, id);
                if(flag)
                {
                    JOptionPane.showMessageDialog(this, "Vehículo Agregado Correctamente!");
                    this.dispose();
                }
                else
                {
                    JOptionPane.showMessageDialog(this, "Error, Compruebe Los Datos Ingresados");
                }
            }
            else
            {
                boolean check = this.controller.getVehicleController().update(this.vehicle, description, id);
                if(check)
                {
                    JOptionPane.showMessageDialog(this, "Vehículo Actualzado Correctamente!");
                    this.dispose();
                }
                else
                {
                    JOptionPane.showMessageDialog(this, "Error, Compruebe Los Datos Ingresados");
                }
            }
            
        }

    }//GEN-LAST:event_btnAddVehicleActionPerformed

    public void bindingModel(Vehicle vehicle)
    {
        this.lblTitle.setText("Modificar Vehículo");
        this.vehicle = vehicle;
        this.txtDescription.setText(vehicle.getDescription());
        String fuel = vehicle.getFuel().getId() + "# " + vehicle.getFuel().getName();
        this.combFuels.setSelectedItem(fuel);
        //this.txtValue.setText((int) fuel.getValue() + "");        
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddVehicle;
    private javax.swing.JButton btnCancel;
    private javax.swing.JComboBox<String> combFuels;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblNombre1;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTextField txtDescription;
    // End of variables declaration//GEN-END:variables
}
